# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
    branches:
        include:
            - master

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle

jobs:

- job: Build
  steps:
  - checkout: self
    submodules: true
  - task: Cache@2
    inputs:
        key: 'gradle | "$(Agent.OS)" | **/build.gradle.kts | **/build.gradle' # Swap build.gradle.kts for build.gradle when using Groovy
        restoreKeys: |
            gradle | "$(Agent.OS)"
            gradle
        path: $(GRADLE_USER_HOME)
    displayName: Configure gradle caching
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: ':app:assembleRelease'
      options: '--build-cache'
  - script: |   
      # stop the Gradle daemon to ensure no files are left open (impacting the save cache operation later)
      ./gradlew --stop    
    displayName: Build
  - task: AndroidSigning@3
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    inputs:
      apkFiles: '**/*.apk'
      apksignerKeystoreFile: 'en-YCH.jks'
      apksignerKeystorePassword: '$(keyStorePassword)'
      apksignerKeystoreAlias: '$(keyAlias)'
      apksignerKeyPassword: '$(keyPassword)'
  - task: CopyFiles@2
    inputs:
      Contents: '**/*.apk'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      CleanTargetFolder: true
      flattenFolders: true
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: APK

- job: Pull
  
  steps:
  - checkout: self
  - script: |
      git config --global user.name "QNotified Auto Deploy Bot"
      git config --global user.email "dmca@ioctl.cc"
      git remote rm origin
      git remote add origin https://$(GITHUB_TOKEN)@github.com/Xposed-Modules-Repo/nil.nadph.qnotified.git
      git push -f origin HEAD:master
      cd /Library/Java/JavaVirtualMachines
      ls

- job: Distribute
  dependsOn: Build
  condition: and(succeeded('Build'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  steps:
  - checkout: none
  - download: current
    artifact: APK'
  - task: GitHubRelease@1
    displayName: Github Release Weekly
    condition: contains(variables['Build.SourceVersionMessage'], 'release')
    inputs:
      gitHubConnection: 'github.com_singleNeuron'
      repositoryName: 'Tony0812-dev/QNotified'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: $(Build.BuildNumber)
      title: '$(Build.SourceVersionMessage)'
      releaseNotesSource: 'inline'
      releaseNotesInline: '$(Build.SourceVersionMessage)'
      assets: '$(Pipeline.Workspace)/APK/*.apk'
      addChangeLog: false
